/*
 * Michael Botros
 * November 27th, 2019
 * This program will convert vrobits to the correct amount of alternative currencies and displays the resulting coins
 */

/**
 *
 * @author mibot3117
 */
public class frmZirboin extends javax.swing.JFrame {
//declaring all variables for the currencies and remainder
int vrobitAmount;
int drobzits;
int clickwicks;
int gazoontights;
int frazoints;
int blointoints;
int vrobitRemainder;
    /**
     * Creates new form frmZirboin
     */
    public frmZirboin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlZirboin = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        txtVrobits = new javax.swing.JTextField();
        lblInstructions = new javax.swing.JLabel();
        lblDrobzits = new javax.swing.JLabel();
        btnExchange = new javax.swing.JButton();
        lblDrobzitsAmount = new javax.swing.JLabel();
        lblClickwicks = new javax.swing.JLabel();
        lblClickwicksAmount = new javax.swing.JLabel();
        lblGazoontights = new javax.swing.JLabel();
        lblGazoontightsAmount = new javax.swing.JLabel();
        lblFrazoints = new javax.swing.JLabel();
        lblFrazointsAmount = new javax.swing.JLabel();
        lblBlointoints = new javax.swing.JLabel();
        lblBlointointsAmount = new javax.swing.JLabel();
        lblVrobits = new javax.swing.JLabel();
        lblVrobitsAmount = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlZirboin.setBackground(new java.awt.Color(0, 102, 0));
        pnlZirboin.setForeground(new java.awt.Color(0, 51, 0));

        lblTitle.setFont(new java.awt.Font("TI Uni", 0, 18)); // NOI18N
        lblTitle.setText("PLANET ZIRBOIN CURRENCY EXCHANGE");

        txtVrobits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVrobitsActionPerformed(evt);
            }
        });

        lblInstructions.setFont(new java.awt.Font("TI Uni", 0, 12)); // NOI18N
        lblInstructions.setText("Enter the number of vrobits you'd like to exchange:");

        lblDrobzits.setFont(new java.awt.Font("TI Uni", 0, 12)); // NOI18N
        lblDrobzits.setText("The amount of drobzits:");

        btnExchange.setBackground(new java.awt.Color(0, 102, 0));
        btnExchange.setFont(new java.awt.Font("TI Uni", 0, 14)); // NOI18N
        btnExchange.setText("Exchange");
        btnExchange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExchangeActionPerformed(evt);
            }
        });

        lblDrobzitsAmount.setText("0");

        lblClickwicks.setFont(new java.awt.Font("TI Uni", 0, 12)); // NOI18N
        lblClickwicks.setText("The amount of clickwicks:");

        lblClickwicksAmount.setText("0");

        lblGazoontights.setFont(new java.awt.Font("TI Uni", 0, 12)); // NOI18N
        lblGazoontights.setText("The amount of gazoontights:");

        lblGazoontightsAmount.setText("0");

        lblFrazoints.setFont(new java.awt.Font("TI Uni", 0, 12)); // NOI18N
        lblFrazoints.setText("The amount of frazoints:");

        lblFrazointsAmount.setText("0");

        lblBlointoints.setFont(new java.awt.Font("TI Uni", 0, 12)); // NOI18N
        lblBlointoints.setText("The amount of blointoints:");

        lblBlointointsAmount.setText("0");

        lblVrobits.setFont(new java.awt.Font("TI Uni", 0, 12)); // NOI18N
        lblVrobits.setText("The amount of vrobits:");

        lblVrobitsAmount.setText("0");

        javax.swing.GroupLayout pnlZirboinLayout = new javax.swing.GroupLayout(pnlZirboin);
        pnlZirboin.setLayout(pnlZirboinLayout);
        pnlZirboinLayout.setHorizontalGroup(
            pnlZirboinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlZirboinLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(68, 68, 68))
            .addGroup(pnlZirboinLayout.createSequentialGroup()
                .addGroup(pnlZirboinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlZirboinLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblInstructions)
                        .addGap(18, 18, 18)
                        .addGroup(pnlZirboinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnExchange)
                            .addComponent(txtVrobits, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlZirboinLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(pnlZirboinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlZirboinLayout.createSequentialGroup()
                                .addComponent(lblFrazoints)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblFrazointsAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlZirboinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlZirboinLayout.createSequentialGroup()
                                    .addComponent(lblGazoontights)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblGazoontightsAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlZirboinLayout.createSequentialGroup()
                                    .addComponent(lblClickwicks)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblClickwicksAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(12, 12, 12)))
                            .addGroup(pnlZirboinLayout.createSequentialGroup()
                                .addComponent(lblBlointoints)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblBlointointsAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlZirboinLayout.createSequentialGroup()
                                .addComponent(lblVrobits)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblVrobitsAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlZirboinLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(lblDrobzits)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDrobzitsAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        pnlZirboinLayout.setVerticalGroup(
            pnlZirboinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlZirboinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(45, 45, 45)
                .addGroup(pnlZirboinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVrobits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInstructions))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExchange)
                .addGap(11, 11, 11)
                .addGroup(pnlZirboinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDrobzits)
                    .addComponent(lblDrobzitsAmount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlZirboinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClickwicks)
                    .addComponent(lblClickwicksAmount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlZirboinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGazoontights)
                    .addComponent(lblGazoontightsAmount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlZirboinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFrazoints)
                    .addComponent(lblFrazointsAmount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlZirboinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBlointoints)
                    .addComponent(lblBlointointsAmount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlZirboinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVrobits)
                    .addComponent(lblVrobitsAmount))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlZirboin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlZirboin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtVrobitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVrobitsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVrobitsActionPerformed

    private void btnExchangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExchangeActionPerformed
        //when you press the "exchange" button, the code takes the vrobit input and converts it by dividing by each currency and displays the output
        vrobitAmount = Integer.parseInt(txtVrobits.getText());
        
        //this segment of code will take the vrobit amount, divide it to get the currency amount, and then it takes the remainder and moves it down the list
        drobzits = vrobitAmount/100000;
        vrobitRemainder = vrobitAmount%100000;
        clickwicks = vrobitRemainder/50000;
        vrobitRemainder = vrobitRemainder%50000;
        gazoontights = vrobitRemainder/10000;
        vrobitRemainder = vrobitRemainder%10000;
        frazoints = vrobitRemainder/1000;
        vrobitRemainder = vrobitRemainder%1000;
        blointoints = vrobitRemainder/500;
        vrobitRemainder = vrobitRemainder%500;
        
        //displays the output to the GUI
        lblDrobzitsAmount.setText(String.valueOf(drobzits));
        lblClickwicksAmount.setText(String.valueOf(clickwicks));
        lblGazoontightsAmount.setText(String.valueOf(gazoontights));
        lblFrazointsAmount.setText(String.valueOf(frazoints));
        lblBlointointsAmount.setText(String.valueOf(blointoints));
        lblVrobitsAmount.setText(String.valueOf(vrobitRemainder));
        
    }//GEN-LAST:event_btnExchangeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmZirboin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmZirboin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmZirboin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmZirboin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmZirboin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExchange;
    private javax.swing.JLabel lblBlointoints;
    private javax.swing.JLabel lblBlointointsAmount;
    private javax.swing.JLabel lblClickwicks;
    private javax.swing.JLabel lblClickwicksAmount;
    private javax.swing.JLabel lblDrobzits;
    private javax.swing.JLabel lblDrobzitsAmount;
    private javax.swing.JLabel lblFrazoints;
    private javax.swing.JLabel lblFrazointsAmount;
    private javax.swing.JLabel lblGazoontights;
    private javax.swing.JLabel lblGazoontightsAmount;
    private javax.swing.JLabel lblInstructions;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblVrobits;
    private javax.swing.JLabel lblVrobitsAmount;
    private javax.swing.JPanel pnlZirboin;
    private javax.swing.JTextField txtVrobits;
    // End of variables declaration//GEN-END:variables
}
